# Generated by Django 4.2.11 on 2026-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='укажите язык программирования')),
                ('description', models.TextField(verbose_name='описание языка программирования')),
                ('image', models.ImageField(upload_to='proglang/', verbose_name='изображение языка программирования')),
                ('crated_date_lang', models.PositiveIntegerField(blank=True, verbose_name='год создания языка программирования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'язык программирования',
                'verbose_name_plural': 'языки программирования',
            },
        ),
    ]
