# Generated by Django 4.2.11 on 2026-02-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progland',
            name='file_python',
            field=models.FileField(null=True, upload_to='files/', verbose_name='загрузите какой нибудь файл'),
        ),
        migrations.AddField(
            model_name='progland',
            name='viki_url',
            field=models.URLField(null=True, verbose_name='вставьте ссылку с википедии'),
        ),
    ]
