# Generated by Django 4.2.11 on 2026-02-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0002_progland_file_python_progland_viki_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progland',
            new_name='ProgLang',
        ),
    ]
