# Generated by Django 6.0.2 on 2026-02-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0003_rename_progland_proglang'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
